spring:
  datasource:
    url: jdbc:h2:file:./data/product
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties: 
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect